# Default values for autonp-operator client
replicaCount: 1

image:
  repository: autonp/operator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Server connection configuration
server:
  host: auto-np-server
  port: 50051
  useTLS: true

# JWT Authentication configuration
auth:
  # If using a secret instead of direct token value
  existingSecret: ""
  secretKey: "token"

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi 