// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cloud/v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StreamService_StreamFlowKeyCount_FullMethodName = "/cloud.v1.StreamService/StreamFlowKeyCount"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	// Bi-directional streaming RPC
	StreamFlowKeyCount(ctx context.Context, opts ...grpc.CallOption) (StreamService_StreamFlowKeyCountClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) StreamFlowKeyCount(ctx context.Context, opts ...grpc.CallOption) (StreamService_StreamFlowKeyCountClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_StreamFlowKeyCount_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceStreamFlowKeyCountClient{stream}
	return x, nil
}

type StreamService_StreamFlowKeyCountClient interface {
	Send(*StreamFlowKeyCountRequest) error
	Recv() (*StreamFlowKeyCountResponse, error)
	grpc.ClientStream
}

type streamServiceStreamFlowKeyCountClient struct {
	grpc.ClientStream
}

func (x *streamServiceStreamFlowKeyCountClient) Send(m *StreamFlowKeyCountRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamServiceStreamFlowKeyCountClient) Recv() (*StreamFlowKeyCountResponse, error) {
	m := new(StreamFlowKeyCountResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	// Bi-directional streaming RPC
	StreamFlowKeyCount(StreamService_StreamFlowKeyCountServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) StreamFlowKeyCount(StreamService_StreamFlowKeyCountServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamFlowKeyCount not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_StreamFlowKeyCount_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServiceServer).StreamFlowKeyCount(&streamServiceStreamFlowKeyCountServer{stream})
}

type StreamService_StreamFlowKeyCountServer interface {
	Send(*StreamFlowKeyCountResponse) error
	Recv() (*StreamFlowKeyCountRequest, error)
	grpc.ServerStream
}

type streamServiceStreamFlowKeyCountServer struct {
	grpc.ServerStream
}

func (x *streamServiceStreamFlowKeyCountServer) Send(m *StreamFlowKeyCountResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamServiceStreamFlowKeyCountServer) Recv() (*StreamFlowKeyCountRequest, error) {
	m := new(StreamFlowKeyCountRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlowKeyCount",
			Handler:       _StreamService_StreamFlowKeyCount_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cloud/v1/message.proto",
}
