{{- if not .Values.operator.cilium.disableFlows }}
{{- $gkeNamespaceExists := false }}
{{- $kubeSystemExists := false }}

{{- /* Check if GKE Dataplane V2 namespace exists */ -}}
{{- range $ns := (lookup "v1" "Namespace" "" "").items }}
  {{- if eq $ns.metadata.name "gke-managed-dpv2-observability" }}
    {{- $gkeNamespaceExists = true }}
  {{- end }}
  {{- if eq $ns.metadata.name "kube-system" }}
    {{- $kubeSystemExists = true }}
  {{- end }}
{{- end }}

{{- if $gkeNamespaceExists }}
---
# Role for accessing Hubble TLS certificates in GKE Dataplane V2 namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-hubble-secrets
  namespace: gke-managed-dpv2-observability
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
rules:
  # Allow reading Hubble TLS certificate secrets in GKE Dataplane V2 namespace
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: 
      - "hubble-relay-client-certs"
      - "hubble-relay-server-certs"
    verbs: ["get"]

---
# RoleBinding for GKE Dataplane V2 namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-hubble-secrets
  namespace: gke-managed-dpv2-observability
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-hubble-secrets
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- if $kubeSystemExists }}
---
# Role for accessing Hubble TLS certificates in kube-system namespace (fallback)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-hubble-secrets
  namespace: kube-system
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
rules:
  # Allow reading Hubble TLS certificate secrets in kube-system namespace
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: 
      - "hubble-relay-client-certs"
      - "hubble-relay-server-certs"
    verbs: ["get"]

---
# RoleBinding for kube-system namespace (fallback)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-hubble-secrets
  namespace: kube-system
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-hubble-secrets
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }} 