apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "kestrel-operator.fullname" . }}-cleanup-runtime-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "kestrel-operator.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ include "kestrel-operator.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
        - name: cleanup
          image: bitnami/kubectl:1.30
          imagePullPolicy: IfNotPresent
          command: ["kubectl"]
          args:
            - "-n"
            - "{{ .Release.Namespace }}"
            - "delete"
            - "secret"
            - "kestrel-operator-jwt-runtime"
            - "--ignore-not-found"