{{- if and .Values.certificates .Values.certificates.client .Values.certificates.client.cert }}
{{- $clientCert := .Values.certificates.client.cert | toString }}
{{- if and $clientCert (contains "BEGIN CERTIFICATE" $clientCert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-client-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
    component: mtls-client
type: kubernetes.io/tls
data:
  # Client certificate for mTLS authentication (unique per operator deployment)
  tls.crt: {{ .Values.certificates.client.cert | b64enc }}
  # Client private key for mTLS authentication (unique per operator deployment)
  tls.key: {{ .Values.certificates.client.key | b64enc }}
  # CA certificate for server verification
  ca.crt: {{ .Values.certificates.ca.cert | b64enc }}
  # Alternative names for backward compatibility with stream_client.go
  client.crt: {{ .Values.certificates.client.cert | b64enc }}
  client.key: {{ .Values.certificates.client.key | b64enc }}
{{- else }}
{{- fail "mTLS is enabled but certificates in values.yaml appear to be placeholders. Please ensure you downloaded the values file from Kestrel Cloud UI which includes real generated certificates." }}
{{- end }}
{{- else }}
{{- fail "mTLS is enabled but no certificates found in values.yaml. Please ensure you downloaded the values file from Kestrel Cloud UI which includes generated certificates." }}
{{- end }}
