apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  # Allow managing secrets in the {{ .Release.Namespace }} namespace only
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing deployments in the {{ .Release.Namespace }} namespace for certificate renewal (self-restart)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"] 