{{- if .Values.operator.trivy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kestrel-operator.fullname" . }}-trivy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kestrel-operator.labels" . | nindent 4 }}
    component: trivy-scanner
spec:
  # Headless service so the operator can discover individual pod IPs per node
  clusterIP: None
  ports:
    - port: {{ .Values.operator.trivy.serverPort }}
      targetPort: trivy-http
      protocol: TCP
      name: http-trivy
  selector:
    {{- include "kestrel-operator.selectorLabels" . | nindent 4 }}
    component: trivy-scanner
{{- end }}
