apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        {{- include "autonp-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Server connection configuration
            - name: SERVER_HOST
              value: "{{ .Values.server.host }}"
            - name: SERVER_PORT
              value: "{{ .Values.server.port }}"
            - name: SERVER_USE_TLS
              value: "{{ .Values.server.useTLS }}"
            
            # Pod namespace for self-identification
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
                  
            # JWT Authentication configuration
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-jwt
                  key: token
            
            # Cilium integration configuration
            - name: DISABLE_CILIUM_FLOWS
              value: "{{ .Values.operator.cilium.disableFlows }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}