name: Build Kestrel Operator Image

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to build and push (e.g., v1.0.0, latest)'
        required: true
        default: 'latest'
        type: string

env:
  REGISTRY: ghcr.io
  
jobs:
  build-and-push:
    name: Build and Push Kestrel Operator Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta for operator
      id: meta-operator
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=raw,value=${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and push operator image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-operator.outputs.tags }}
        labels: ${{ steps.meta-operator.outputs.labels }} 